/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package module.ballerinax.wso2.mi.utilities;

import module.ballerinax.wso2.mi.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
