/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package module.ballerinax.wso2.mi.app;

import module.ballerinax.wso2.mi.list.LinkedList;

import static module.ballerinax.wso2.mi.utilities.StringUtils.join;
import static module.ballerinax.wso2.mi.utilities.StringUtils.split;
import static module.ballerinax.wso2.mi.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
